COLUMN_NAMES_MAP = {
    "Block/society, Area, Town/District (should be specific, but don't reveal exact address)": "area",
    "Which country?": "country", "Zipcode": "zipcode",
    "Generally what's your reason to be in the area": "reason_in_area",
    "If you selected work, do you generally work outdoors?": "is_work_outdoor",
    "How residential do you think the area is? in terms of buildings and local population": "rate_residential",
    "How commercial do you think the area is? in terms of markets, offices, and shops": "rate_commercial",
    "Compared to other areas, how densely populated/saturated do you think the area is?": "rate_density",
    "Yes/No questions for outdoor area and surroundings [Is there a green area nearby i.e: park, garden?]": "green_area",
    "Yes/No questions for outdoor area and surroundings [Are there sufficient shaded areas in your neighborhood, such as trees or covered structures to hide from the sun & catch breath?]": "sufficient_shade",
    "Yes/No questions for outdoor area and surroundings [Is greenery in the area well maintained?]": "maintained_green_area",
    "Yes/No questions for outdoor area and surroundings [Do you avoid going out because of the heat]": "avoid_going_out",
    "Yes/No questions for outdoor area and surroundings [Do you feel there's lack of infrastructure and heat mitigation planning in your suroundings? ]": "lack_planning_and_infra",
    "Yes/No questions for outdoor area and surroundings [Do public places i.e bus stops etc have easy access to water?]": "easy_water_access",
    "Yes/No questions for outdoor area and surroundings [Is traffic jam a major issue in the area?]": "traffic_jam_issue",
    "Yes/No questions for outdoor area and surroundings [Is temperature of reported area cooler than many areas of city]": "cooler_area",
    "Which month of the year have you reported above? Mark all that apply": "reported_months",
    "During the summer, which times of day do you feel the hottest temperatures in the area? At what time does that start?": "feel_hottest",
    "At what time does it start getting better again?": "feel_better",
    "How would you describe the amount of greenery in your neighborhood? (Are they evenly spread out - cover enough space - provide enough shade for pedestrians) (optional)": "describe_greenery",
    "Is temperature of reported area cooler than many areas of city? If yes, what is the reason. If no, why?": "describe_why_cooler",
    "Do you have to alter your routine when it is hot? Do you make any adaptive changes to your activities (like avoiding going outside during certain times, or using personal vehicles instead of public transport, clothing, carrying something with you, etc)? What are those changes?": "describe_routine_alteration",
    "For how many hours do you use air conditioning.": "AC_use_hours",
    "Have there been any heat related health incidents in this area?": "describe_incidents",
    "Where do you spend most of your time in this area?": "type_of_activity",
    "Is there enough ventilation indoor?": "indoor_ventilation",
    "Do you often feel suffocated indoor when there is a heatwave": "indoor_suffocation",
    "Do you have any other methods you use to keep your home/property cool? If so, please state them.": "describe_indoor_cooling_methods",
    "Do you think any change in area, infrastructure, or surroundings could improve your indoor experience? i.e: design of building, ventilation, hot surfaces, roofs, surrounding area, etc. List anything that comes into your mind which could improve indoor experience": "describe_indoor_improvements",
    "How could your overall outdoor experience during heat wave be improved? Tell measures on governmental, and personal level which can be helpful.": "describe_outdoor_improvements",
    "Do you think bus stops/public waiting areas have sufficient shaded area?": "public_stop_shades",
    "Have you or anyone you know suffered from a case of extreme heat related health issue specifically in the area you have reported?": "is_health_effected",
    "What are the effects of the extreme heat cases on that person(s)?": "describe_health_effect",
    "What were the measures taken to recover from such health effects from the extreme heat?": "Health_recovery_measures",
    "Would you consider consulting a forum/chatbot to help you and community to combat heat and strategically plan for it through experiences of others?": "need_chatbot",
    "Would you like to Add any comments related to Urban heat mitigation planning in your Area specifically by Government other institutes or on personal level.": "final_comment"}
